param(
    [Parameter(Mandatory=$false)]
    [string]$InputPath = ".",
    
    [Parameter(Mandatory=$false)]
    [string]$OutputPath = "./wiki-output",
    
    [Parameter(Mandatory=$false)]
    [switch]$Flatten,
    
    [Parameter(Mandatory=$false)]
    [switch]$InPlace
)

<#
.SYNOPSIS
    Converts XMLDoc2Markdown output to GitHub Wiki compatible format.

.DESCRIPTION
    This script processes markdown files generated by XMLDoc2Markdown and converts them
    to be compatible with GitHub Wiki by:
    - Removing .md extensions from links
    - Removing ./ prefixes from links
    - Optionally flattening all files into a single markdown file
    - Optionally modifying files in place

.NOTES
    Created with assistance from GitHub Copilot

.PARAMETER InputPath
    The path to the directory containing the markdown files. Default is current directory.

.PARAMETER OutputPath
    The path where converted files will be saved. Default is ./wiki-output.
    Ignored if -InPlace is used.

.PARAMETER Flatten
    If specified, all markdown files will be combined into a single file.

.PARAMETER InPlace
    If specified, modifies files in place instead of creating copies.

.EXAMPLE
    .\Convert-ToGitHubWiki.ps1
    Converts all markdown files in current directory to wiki-output folder.

.EXAMPLE
    .\Convert-ToGitHubWiki.ps1 -InPlace
    Modifies all markdown files in place.

.EXAMPLE
    .\Convert-ToGitHubWiki.ps1 -Flatten -OutputPath "./wiki.md"
    Combines all markdown files into a single wiki.md file.
#>

function Convert-MarkdownLinks {
    param(
        [string]$Content,
        [bool]$UseAnchors = $false
    )
    
    if ($UseAnchors) {
        # Convert relative links to anchor links for flattened output
        # Match patterns like [Text](./path/file.md) or [Text](path/file.md)
        $Content = [regex]::Replace($Content, '\[([^\]]+)\]\(\.?/?([^)]+?)(?:\.md)?\)', {
            param($match)
            $linkText = $match.Groups[1].Value
            $linkPath = $match.Groups[2].Value
            
            # Skip external links (http/https)
            if ($linkPath -match '^https?://') {
                return $match.Value
            }
            
            # Convert path to anchor
            # Remove path separators and convert to lowercase
            $anchor = $linkPath -replace '[/\\]', '-' -replace '[^a-zA-Z0-9\s-]', '' -replace '\s+', '-' -replace '-+', '-'
            $anchor = $anchor.ToLower().Trim('-')
            
            return "[$linkText](#$anchor)"
        })
    } else {
        # For GitHub Wiki: Convert links to use only filename (no directory path)
        # Match patterns like [Text](./path/to/file.md) or [Text](path/to/file.md#anchor)
        $Content = [regex]::Replace($Content, '\[([^\]]+)\]\(\.?/?([^)#]+?)(?:\.md)?(#[^)]+)?\)', {
            param($match)
            $linkText = $match.Groups[1].Value
            $linkPath = $match.Groups[2].Value
            $anchor = $match.Groups[3].Value
            
            # Skip external links (http/https)
            if ($linkPath -match '^https?://') {
                return $match.Value
            }
            
            # Extract just the filename from the path (remove directory)
            $filename = Split-Path -Path $linkPath -Leaf
            
            # Return with just filename and optional anchor
            return "[$linkText]($filename$anchor)"
        })
    }
    
    return $Content
}

function Get-MarkdownFiles {
    param(
        [string]$Path,
        [string]$ExcludePath = $null,
        [switch]$ExcludeIndex
    )
    
    $files = Get-ChildItem -Path $Path -Filter "*.md" -Recurse | Where-Object { $_.Name -ne "README.md" }
    
    # Exclude index.md if requested (for flattened output which generates its own TOC)
    if ($ExcludeIndex) {
        $files = $files | Where-Object { $_.Name -ne "index.md" }
    }
    
    # Exclude files in the output directory
    if ($ExcludePath) {
        $excludeFullPath = (Resolve-Path -Path $ExcludePath -ErrorAction SilentlyContinue)
        if ($excludeFullPath) {
            $files = $files | Where-Object { !$_.FullName.StartsWith($excludeFullPath) }
        }
    }
    
    return $files
}

function Flatten-ToSingleFile {
    param(
        [string]$InputPath,
        [string]$OutputFile
    )
    
    Write-Host "Flattening markdown files into single document..." -ForegroundColor Cyan
    
    # Get output directory to exclude it from processing
    $outputDir = Split-Path -Path $OutputFile -Parent
    if ($outputDir) {
        $outputDir = Join-Path -Path $InputPath -ChildPath $outputDir
    }
    
    $files = Get-MarkdownFiles -Path $InputPath -ExcludePath $outputDir -ExcludeIndex | Sort-Object FullName
    
    $combinedContent = @()
    
    # Build mapping of file paths to their heading anchors (filename -> heading anchor)
    $fileToAnchor = @{}
    
    foreach ($file in $files) {
        $relativePath = $file.FullName.Substring($InputPath.Length).TrimStart('\', '/')
        $content = Get-Content -Path $file.FullName -Raw -Encoding UTF8
        
        # Extract first heading
        if ($content -match '^#\s+(.+)') {
            $heading = $matches[1].Trim()
            $anchor = $heading -replace '[^a-zA-Z0-9\s-]', '' -replace '\s+', '-' -replace '-+', '-'
            $anchor = $anchor.ToLower().Trim('-')
            
            # Store mapping: filename (without extension) -> anchor
            $filename = [System.IO.Path]::GetFileNameWithoutExtension($file.Name)
            $fileToAnchor[$filename.ToLower()] = $anchor
            
            # Also store full relative path mapping (with forward slashes, no extension)
            $pathWithoutExt = $relativePath -replace '\.md$', '' -replace '\\', '/'
            $fileToAnchor[$pathWithoutExt.ToLower()] = $anchor
        }
    }
    
    # Add table of contents header
    $combinedContent += "## Table of Contents"
    $combinedContent += ""
    
    # Build hierarchical TOC based on namespace from files
    $tocStructure = @{}
    
    foreach ($file in $files) {
        $relativePath = $file.FullName.Substring($InputPath.Length).TrimStart('\', '/')
        $content = Get-Content -Path $file.FullName -Raw -Encoding UTF8
        
        # Extract first heading and namespace
        $heading = $null
        $namespace = $null
        
        if ($content -match '^#\s+(.+)') {
            $heading = $matches[1].Trim()
        }
        
        if ($content -match 'Namespace:\s*([^\r\n]+)') {
            $namespace = $matches[1].Trim()
        }
        
        if ($heading) {
            $anchor = $heading -replace '[^a-zA-Z0-9\s-]', '' -replace '\s+', '-' -replace '-+', '-'
            $anchor = $anchor.ToLower().Trim('-')
            
            # Use namespace if available, otherwise use root
            $category = if ($namespace) { $namespace } else { '_root' }
            
            if (!$tocStructure.ContainsKey($category)) {
                $tocStructure[$category] = @()
            }
            $tocStructure[$category] += @{ Heading = $heading; Anchor = $anchor }
        }
    }
    
    # Output TOC with sections
    $orderedCategories = $tocStructure.Keys | Sort-Object | Where-Object { $_ -ne '_root' }
    
    # Root items first if any
    if ($tocStructure.ContainsKey('_root')) {
        foreach ($item in $tocStructure['_root']) {
            $combinedContent += "- [$($item.Heading)](#$($item.Anchor))"
        }
        $combinedContent += ""
    }
    
    # Then categorized items
    foreach ($category in $orderedCategories) {
        $combinedContent += "### $category"
        $combinedContent += ""
        foreach ($item in $tocStructure[$category]) {
            $combinedContent += "- [$($item.Heading)](#$($item.Anchor))"
        }
        $combinedContent += ""
    }
    
    $combinedContent += "---"
    $combinedContent += "<br></br>"
    $combinedContent += ""
    
    # Add content from each file
    foreach ($file in $files) {
        $relativePath = $file.FullName.Substring($InputPath.Length).TrimStart('\', '/')
        Write-Host "  Processing: $relativePath"
        
        $content = Get-Content -Path $file.FullName -Raw -Encoding UTF8
        
        # Convert links by replacing each known path with its anchor
        foreach ($path in $fileToAnchor.Keys) {
            $anchor = $fileToAnchor[$path]
            $escapedPath = [regex]::Escape($path)
            # Replace links like [Text](path) with [Text](#anchor)
            $content = $content -replace "\]\($escapedPath\)", "](#$anchor)"
            # Also handle links with existing fragment anchors - preserve the fragment
            # but this is tricky, so for now just do the simple case
        }
        
        # Add source file comment
        $combinedContent += "<!-- Source: $relativePath -->"
        $combinedContent += ""
        
        # Add content
        $combinedContent += $content.TrimEnd()
        $combinedContent += ""
        $combinedContent += "---"
        $combinedContent += "<br></br>"
        $combinedContent += ""
    }
    
    # Ensure output directory exists
    if ($outputDir -and !(Test-Path -Path $outputDir)) {
        New-Item -Path $outputDir -ItemType Directory -Force | Out-Null
    }
    
    # Write combined file
    $combinedContent -join "`n" | Set-Content -Path $OutputFile -Encoding UTF8 -NoNewline
    
    Write-Host "Created flattened file: $OutputFile" -ForegroundColor Green
    Write-Host "Processed $($files.Count) files" -ForegroundColor Green
}

function Convert-Files {
    param(
        [string]$InputPath,
        [string]$OutputPath,
        [bool]$InPlace
    )
    
    Write-Host "Converting markdown files for GitHub Wiki..." -ForegroundColor Cyan
    
    $files = Get-MarkdownFiles -Path $InputPath
    $count = 0
    
    foreach ($file in $files) {
        $relativePath = $file.FullName.Substring($InputPath.Length).TrimStart('\', '/')
        Write-Host "  Processing: $relativePath"
        
        $content = Get-Content -Path $file.FullName -Raw -Encoding UTF8
        $convertedContent = Convert-MarkdownLinks -Content $content
        
        if ($InPlace) {
            $outputFile = $file.FullName
        } else {
            $outputFile = Join-Path -Path $OutputPath -ChildPath $relativePath
            $outputDir = Split-Path -Path $outputFile -Parent
            
            if (!(Test-Path -Path $outputDir)) {
                New-Item -Path $outputDir -ItemType Directory -Force | Out-Null
            }
        }
        
        $convertedContent | Set-Content -Path $outputFile -Encoding UTF8 -NoNewline
        $count++
    }
    
    if ($InPlace) {
        Write-Host "Modified $count files in place" -ForegroundColor Green
    } else {
        Write-Host "Converted $count files to: $OutputPath" -ForegroundColor Green
    }
}

# Main execution
try {
    # Resolve full path
    $InputPath = Resolve-Path -Path $InputPath -ErrorAction Stop
    
    if ($Flatten) {
        # Determine output file path
        if ($OutputPath -like "*.md") {
            $flattenedFile = $OutputPath
        } else {
            $flattenedFile = Join-Path -Path $OutputPath -ChildPath "API-Documentation.md"
        }
        
        Flatten-ToSingleFile -InputPath $InputPath -OutputFile $flattenedFile
    } else {
        if ($InPlace) {
            $confirmation = Read-Host "This will modify files in place. Continue? (y/n)"
            if ($confirmation -ne 'y') {
                Write-Host "Operation cancelled." -ForegroundColor Yellow
                exit
            }
        }
        
        Convert-Files -InputPath $InputPath -OutputPath $OutputPath -InPlace $InPlace
    }
    
    Write-Host "`nConversion complete!" -ForegroundColor Green
    
} catch {
    Write-Host "Error: $_" -ForegroundColor Red
    exit 1
}
