spring.mvc.locale=en
spring.mvc.locale-resolver=fixed
spring.web.locale=en
spring.web.locale-resolver=fixed
spring.messages.fallback-to-system-locale=false
server.error.include-message=never
management.endpoints.web.exposure.include=health,info
logging.file.name=logs/dv-lobby-api.log
logging.level.root=INFO
